name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'

    - name: Prepare Complete Flutter Project
      run: |
        flutter create --org com.serviceyar app_temp
        cp -f lib/main.dart app_temp/lib/main.dart
        cd app_temp
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ServiceYar-APK
        path: app_temp/build/app/outputs/flutter-apk/app-release.apk
