name: Flutter Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          # این بخش اندروید را تولید می‌کند
          flutter create . 
          
          # این بخش minSdkVersion را به 21 تغییر می‌دهد
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle
          sed -i 's/minSdkVersion .*/minSdkVersion 21/g' android/app/build.gradle
          
          # بیلد نهایی
          flutter build apk --release
